apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: login
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:9.0.0
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: postgres.db
            - name: DB_PORT
              value: '5432'
            - name: DB_DATABASE
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: kubernetes.KUBE_PING
            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: namespace=login
            - name: KEYCLOAK_FRONTEND_URL
              value: http://sso.krsdev.local/auth
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: KEYCLOAK_STATISTICS
              value: all
          ports:
            - name: http
              containerPort: 8080
#          readinessProbe:
#            httpGet:
#              port: http
#              path: /realms/master
#          livenessProbe:
#            httpGet:
#              port: http
#              path: /
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: keycloak
      securityContext:
        runAsNonRoot: true
