{
 "title": "Resource overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodes",
    "label": "Nodes",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "namespaces",
    "label": "Namespaces",
    "query": "label_values(kube_pod_info, exported_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU totals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$nodes\", exported_namespace=~\"$namespaces\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$nodes\", exported_namespace=~\"$namespaces\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(rate((\n  container_cpu_usage_seconds_total{container!=\"\"} *\n  on (namespace, pod) group_left(node)\n  label_replace(\n    kube_pod_info{node=~\"$nodes\", exported_namespace=~\"$namespaces\"},\n  \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")\n)[$__interval:]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$nodes\"})",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "Memory totals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$nodes\", exported_namespace=~\"$namespaces\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$nodes\", exported_namespace=~\"$namespaces\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(\n  container_memory_working_set_bytes{container!=\"\"} *\n  on (namespace, pod) group_left(node)\n  label_replace(\n    kube_pod_info{node=~\"$nodes\", exported_namespace=~\"$namespaces\"},\n  \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\")\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$nodes\"})",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$nodes\", exported_namespace=~\"$namespaces\"}"
    },
    {
     "expr": "kube_pod_info{node=\"$nodes\", exported_namespace=~\"$namespaces\"} * on (exported_namespace, pod)\nsum(kube_pod_container_resource_requests_cpu_cores) by (exported_namespace, pod)"
    },
    {
     "expr": "kube_pod_info{node=\"$nodes\", exported_namespace=~\"$namespaces\"} * on (exported_namespace, pod)\nsum(kube_pod_container_resource_limits_cpu_cores) by (exported_namespace, pod)"
    },
    {
     "expr": "kube_pod_info{node=\"$nodes\", exported_namespace=~\"$namespaces\"} * on (exported_namespace, pod)\nsum(kube_pod_container_resource_requests_memory_bytes) by (exported_namespace, pod)"
    },
    {
     "expr": "kube_pod_info{node=\"$nodes\", exported_namespace=~\"$namespaces\"} * on (exported_namespace, pod)\nsum(kube_pod_container_resource_limits_memory_bytes) by (exported_namespace, pod)"
    }
   ]
  }
 ]
}