global:
  evaluation_interval: 15s
  scrape_interval: 15s

rule_files:
- alerts.yaml
- rules.yaml

scrape_configs:
- job_name: kubernetes-apiservers
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    - __meta_kubernetes_service_name
    - __meta_kubernetes_namespace
    regex: https;kubernetes;default
  - replacement: kubernetes.default:443
    target_label: __address__

- job_name: kubernetes-nodes
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - replacement: kubernetes.default:443
    target_label: __address__
  - source_labels:
    - __meta_kubernetes_node_name
    replacement: /api/v1/nodes/$1/proxy/metrics
    target_label: __metrics_path__
  - source_labels:
    - __meta_kubernetes_node_name
    target_label: node

- job_name: kubernetes-nodes-cadvisor
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - replacement: kubernetes.default:443
    target_label: __address__
  - source_labels:
    - __meta_kubernetes_node_name
    replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
    target_label: __metrics_path__
  - source_labels:
    - __meta_kubernetes_node_name
    target_label: node

- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
    regex: true
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_path
    regex: (.+)
    target_label: __metrics_path__
  - source_labels:
    - __address__
    - __meta_kubernetes_pod_annotation_prometheus_io_port
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_skip_labels
    - __meta_kubernetes_pod_node_name
    regex: (?:|false);(.+)
    target_label: node
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_skip_labels
    - __meta_kubernetes_namespace
    regex: (?:|false);(.+)
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_skip_labels
    - __meta_kubernetes_pod_name
    regex: (?:|false);(.+)
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_skip_labels
    - __meta_kubernetes_pod_label_app
    regex: (?:|false);(.+)
    target_label: app
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_skip_labels
    - __meta_kubernetes_pod_label_version
    regex: (?:|false);(.+)
    target_label: version
