{
 "title": "Pod overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, exported_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{exported_namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}[$__interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{exported_namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{exported_namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{exported_namespace=\"$namespace\",pod=\"$pod\"}[$__range])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Previous restart",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{exported_namespace=\"$namespace\",pod=\"$pod\"} == 1",
     "legendFormat": "{{container}}: {{reason}}"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{exported_namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{exported_namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Error counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\",pod=\"$pod\"}[$__interval] |~ \"(?i)warn|err|fatal\"))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\",pod=\"$pod\"} |~ \"(?i)warn|err|fatal\""
    }
   ]
  }
 ]
}