apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:8080
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
