apiVersion: v1
kind: ConfigMap
metadata:
  name: initialize
  namespace: login
data:
  initialize.sh: |
    #!/bin/bash
    set -e
    export PATH="/opt/jboss/keycloak/bin:$PATH"

    kcadm.sh config credentials \
      --server http://keycloak:8080/auth \
      --realm master \
      --user admin \
      --password admin

    admin_id=$(
      kcadm.sh get users \
        --fields id \
        --query username=admin \
        --format csv | \
      tr -d '"'
    )

    kcadm.sh update "users/$admin_id" \
      --set email=admin@localhost \
      --set emailVerified=true

    client_id=$(
      kcadm.sh create clients \
        --id \
        --set clientId=grafana \
        --set redirectUris='["http://grafana.krsdev.local/*"]' \
        --set secret=secret
    )
    echo "Created new client with id '$client_id'"

    kcadm.sh create "clients/$client_id/protocol-mappers/models" \
      --set protocol=openid-connect \
      --set name=Roles \
      --set protocolMapper=oidc-usermodel-realm-role-mapper \
      --set config.multivalued=true \
      --set 'config."claim.name"=roles' \
      --set 'config."jsonType.label"=String' \
      --set 'config."userinfo.token.claim"=true'

    curl --request POST --silent --fail http://localhost:15020/quitquitquit
